### PR TITLE
Specify UTF-8 encoding because... Windows

### LINKED ISSUE #140: Character encoding on saved files needed in Windows
WTL 0.11.4

The default encoding in Windows 10 (cp1252) for Python < 3.9 may case exceptions on some pages.
Since I always want UTF-8, I patched the `open` calls in snapshot.py like so:
```(path / "source.html", "w", encoding="utf8")```

I'm not up to speed on the latest Python development, and this problem may go away in later Python versions.
See e.g. https://www.python.org/dev/peps/pep-0597/

```
  File "C:\Users\pikand\AppData\Local\Programs\Python\Python38\lib\site-packages\webtraversallibrary\snapshot.py", line 293, in save
    f.write(str(self.page_source))
  File "C:\Users\pikand\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36954-36960: character maps to <undefined>
```

### PR DESCRIPTION
**Pull request by naslundx**
Fixes #140

### CODE REVIEW

**Comment by vonNiklasson** [comment]
Out of interest, does Windows use `Unicode` or `Windows-1252` by default? Or is it random depending on the runtime?

**Comment by vonNiklasson** [comment]
I did a quick scan for other occurrences, here are a few. I appreciate that the tests may be overkill, since they is usually run on defined unix instances.

## Tests
 - [/tests/site/flask_app.py#L44](https://github.com/klarna-incubator/webtraversallibrary/blob/db6d4bf9af9119cac9b8188344d824f32999d845/tests/site/flask_app.py#L44)
 - [/tests/site/flask_app.py#64](https://github.com/klarna-incubator/webtraversallibrary/blob/db6d4bf9af9119cac9b8188344d824f32999d845/tests/site/flask_app.py#64)
 - [/tests/site/flask_app.py#85](https://github.com/klarna-incubator/webtraversallibrary/blob/db6d4bf9af9119cac9b8188344d824f32999d845/tests/site/flask_app.py#85)
 - [/tests/site/flask_app.py#103](https://github.com/klarna-incubator/webtraversallibrary/blob/db6d4bf9af9119cac9b8188344d824f32999d845/tests/site/flask_app.py#103)
 - [/tests/site/flask_app.py#116](https://github.com/klarna-incubator/webtraversallibrary/blob/db6d4bf9af9119cac9b8188344d824f32999d845/tests/site/flask_app.py#116)

## Examples
- [/examples/without_workflow.py#L54](https://github.com/klarna-incubator/webtraversallibrary/blob/db6d4bf9af9119cac9b8188344d824f32999d845/examples/without_workflow.py#L54)

## Scraper
- [/webtraversallibrary/scraper.py#L189](https://github.com/klarna-incubator/webtraversallibrary/blob/b936d78f4b8aaaf29995133e908ed20d4b69e302/webtraversallibrary/scraper.py#L189)

## Javascript.py
- [/webtraversallibrary/javascript.py#L323](https://github.com/klarna-incubator/webtraversallibrary/blob/f101f64918c94e889396833f1a4ad790453baeca/webtraversallibrary/javascript.py#L323)

**Comment by naslundx** [comment]
> Out of curiosity, does Windows use `Unicode` or `Windows-1252` by default? Or is it "random" depending on the runtime?

It's a looooong story:
https://discuss.python.org/t/pep-597-use-utf-8-for-default-text-file-encoding/1819

**Comment by naslundx** [comment]
@vonNiklasson Updated! Didn't update the one in scraper because it's reading binary data.

**Comment by vonNiklasson** [comment]
[So close](https://github.com/klarna-incubator/webtraversallibrary/pull/149/checks?check_run_id=1885906472#step:8:11)
```
./tests/site/flask_app.py:64:121: E501 line too long (121 > 120 characters)
```

**Review by vonNiklasson — APPROVED** [review]

**Comment by naslundx** [comment]
WHAT THE

**Pull request merged**
