### PR TITLE
Removed XPATH generation, noone cares

### PR DESCRIPTION
**Pull request by naslundx**
Fixes (ish) #137 

XPATH selector isn't supported anywhere else in WTL, so doesn't really make sense to support it. Let's add back support in the future (across the board) if needed.

### CODE REVIEW

**Comment by vonNiklasson** [comment]
Looks fine, except there's still [this one lonely guy](https://github.com/klarna-incubator/webtraversallibrary/blob/d1fba64fdd32373c336e232e5387b7dbfc2e8bfd/webtraversallibrary/scraper.py#L212) left.

- [ ] Should it be there?

**Review by vonNiklasson — COMMENTED** [review]
Looks fine, except there's still [this one lonely guy](https://github.com/klarna-incubator/webtraversallibrary/blob/d1fba64fdd32373c336e232e5387b7dbfc2e8bfd/webtraversallibrary/scraper.py#L212) left.

- [x] Should it be there?

**Comment by redfungus** [comment]
Hi!
We actually use the xpath selector quite a lot.
Is this open for reconsidering?

**Comment by naslundx** [comment]
@redfungus Oh, I didn't know! How do you use it exactly? There is no actual support inside WTL

**Comment by redfungus** [comment]
> @redfungus Oh, I didn't know! How do you use it exactly? There is no actual support inside WTL

We just read it to use as features to compare distances between DOM elements. It can technically also be done with the css selector with some changes.

**Comment by naslundx** [comment]
Upon request I will redo this so that xpath field is still generated but readonly.

**Pull request closed without merging**
